export const ADD_TRANSACTION_FULFILLED = 'ADD_TRANSACTION_FULFILLED'
export const ADD_TRANSACTION_PENDING = 'ADD_TRANSACTION_PENDING'
export const ADD_TRANSACTION_REJECTED = 'ADD_TRANSACTION_REJECTED'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'

export const REMOVE_TRANSACTION_FULFILLED = 'REMOVE_TRANSACTION_FULFILLED'
export const REMOVE_TRANSACTION_PENDING = 'REMOVE_TRANSACTION_PENDING'
export const REMOVE_TRANSACTION_REJECTED = 'REMOVE_TRANSACTION_REJECTED'
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION'

export const SUBMIT_TRANSACTION_FULFILLED = 'SUBMIT_TRANSACTION_FULFILLED'
export const SUBMIT_TRANSACTION_PENDING = 'SUBMIT_TRANSACTION_PENDING'
export const SUBMIT_TRANSACTION_REJECTED = 'SUBMIT_TRANSACTION_REJECTED'
export const SUBMIT_TRANSACTION = 'SUBMIT_TRANSACTION'
